[project]
name = "gem-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.21.0",
    "pytest>=9.0.2",
    "rich>=14.3.3",
]
